# File: .github/workflows/lint-test.yml
name: Linting 
description: 'Check the code with Linting'

runs:
  using: "composite"
  steps:
      - name: Lint with flake8
        shell: bash
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Pylint
        shell: bash
        run: |
          pylint $(git ls-files '*.py')


