# File: .github/workflows/install-packages.yml
name: 'Install Python Packages'
description: 'Install Python Packages'

runs:
  using: "composite"
  steps:
      - name: Add conda to system path
        shell: bash
        run: |
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install tools from PyPI
        shell: bash
        run: |
          pip install pylint
          pip install flask
          pip install psutil
          pip install pymongo
          pip install hvac
          pip install flake8
          pip install pytest
          pip install flask-testing
          pip install -r requirements.txt
